### ISSUE TITLE
Current version not installing on Python 3.13

### ISSUE THREAD

**Issue by eelcodoornbos** [ancklo/ChaosMagPy#12]
Our IT department recently upgraded us to Python 3.13, and this caused some trouble installing ChaosMagPy for me, due to removal of some deprecated feature. I got this error on installing with pip:

>       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

I managed to fix it in my environment after consulting this Stack Overflow article: https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

Cloning the repository and changing the numpy version to the exact version `numpy==1.26.4` in pyproject.toml seems to have worked.

**Comment by ancklo** [comment]
Thanks for sharing this fix.

There will soon be a new release of ChaosMagPy with updated dependencies which should fix this automatically. In any case, we found that the following setup works with Python 3.13:

* python==3.13
* numpy==2.2.5
* hdf5storage==0.2
* other dependencies as listed in the installation guide

However, to use these specific versions with the current chaosmagpy release (v0.14), one needs to overwrite the dependencies in the pip installer. This can be done with:

`pip install --no-dependencies chaosmagpy`
